apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-demo-kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: banking-demo
  source:
    repoURL: https://github.com/Rayloveyou/Banking-Demo.git
    targetRevision: main
    path: phase2-helm-chart/banking-demo/template-infra
    helm:
      releaseName: banking-demo-kong
      valueFiles:
        - ../charts/kong/values.yaml
      parameters:
        - name: serviceName
          value: kong
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
